import os
import logging
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from typing import Optional
import uuid

from sqlalchemy.orm import Session
from models.escalation import Escalation

logger = logging.getLogger("escalation_service")

# ── Feature flag: set ESCALATION_EMAIL_ENABLED=true in .env to activate SMTP alerts ──
ESCALATION_EMAIL_ENABLED = os.getenv("ESCALATION_EMAIL_ENABLED", "false").lower() == "true"

SMTP_HOST = os.getenv("SMTP_HOST", "")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER = os.getenv("SMTP_USER", "")
SMTP_PASS = os.getenv("SMTP_PASS", "")
ALERT_RECIPIENT_EMAIL = os.getenv("ALERT_RECIPIENT_EMAIL", "")


class EscalationService:
    """
    Automated escalation service for HIGH_CONCERN and IMMEDIATE_SAFETY risk events.

    Architecture:
    1. Every high-risk message ALWAYS creates a DB Escalation record (audit trail).
    2. Real email delivery is feature-flagged off by default (ESCALATION_EMAIL_ENABLED=false)
       so the app works without SMTP credentials configured.
    3. This service is intentionally NOT the primary safety floor — RiskClassifier regex
       rules run independently and win if they disagree upward (see routers/chat.py).
    """

    # Risk levels that trigger automated escalation
    ESCALATION_TRIGGER_LEVELS = {"HIGH_CONCERN", "IMMEDIATE_SAFETY"}

    @classmethod
    def trigger(
        cls,
        db: Session,
        user_id: uuid.UUID,
        conversation_id: Optional[uuid.UUID],
        risk_level: str,
        reason: str,
    ) -> Optional[Escalation]:
        """
        Trigger an escalation event. Always logs to DB. Optionally sends email if enabled.

        Returns the created Escalation record, or None if risk level doesn't warrant escalation.
        """
        if risk_level not in cls.ESCALATION_TRIGGER_LEVELS:
            return None

        channel = "helpline_demo_log"
        status = "pending"

        # Attempt email delivery if feature flag is enabled
        if ESCALATION_EMAIL_ENABLED:
            email_sent = cls._send_email_alert(
                user_id=user_id,
                risk_level=risk_level,
                reason=reason,
                triggered_at=datetime.utcnow(),
            )
            if email_sent:
                channel = "smtp_email"
                status = "notified"
            else:
                logger.warning("[EscalationService] Email delivery failed, falling back to demo log.")

        # Always persist escalation record to DB
        escalation = Escalation(
            user_id=user_id,
            conversation_id=conversation_id,
            risk_level=risk_level,
            reason=reason,
            triggered_at=datetime.utcnow(),
            notified_channel=channel,
            status=status,
        )
        db.add(escalation)
        db.flush()  # Flush so we get the ID without committing the outer transaction

        logger.warning(
            f"[EscalationService] ESCALATION TRIGGERED | "
            f"user={user_id} | level={risk_level} | channel={channel} | "
            f"reason={reason[:120]}"
        )

        return escalation

    @classmethod
    def _send_email_alert(
        cls,
        user_id: uuid.UUID,
        risk_level: str,
        reason: str,
        triggered_at: datetime,
    ) -> bool:
        """
        SMTP email delivery stub. Reads credentials from environment variables.
        Returns True if email was sent successfully, False otherwise.

        To enable: set ESCALATION_EMAIL_ENABLED=true and configure SMTP_HOST,
        SMTP_USER, SMTP_PASS, ALERT_RECIPIENT_EMAIL in your .env file.
        """
        if not all([SMTP_HOST, SMTP_USER, SMTP_PASS, ALERT_RECIPIENT_EMAIL]):
            logger.error("[EscalationService] SMTP credentials incomplete — email not sent.")
            return False

        try:
            subject = f"[Teen Wellbeing Alert] {risk_level} — Immediate Attention Required"
            body = (
                f"An automated escalation has been triggered.\n\n"
                f"Risk Level: {risk_level}\n"
                f"Triggered At: {triggered_at.isoformat()}\n"
                f"User ID: {user_id}\n\n"
                f"Reason:\n{reason}\n\n"
                f"---\n"
                f"Please review this case in the counselor dashboard at /alerts.\n"
                f"This alert was generated by the Teen Wellbeing Intelligence system."
            )

            msg = MIMEMultipart()
            msg["From"] = SMTP_USER
            msg["To"] = ALERT_RECIPIENT_EMAIL
            msg["Subject"] = subject
            msg.attach(MIMEText(body, "plain"))

            with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=10) as server:
                server.ehlo()
                server.starttls()
                server.login(SMTP_USER, SMTP_PASS)
                server.sendmail(SMTP_USER, ALERT_RECIPIENT_EMAIL, msg.as_string())

            logger.info(f"[EscalationService] Alert email sent to {ALERT_RECIPIENT_EMAIL}")
            return True

        except Exception as e:
            logger.error(f"[EscalationService] SMTP error: {e}")
            return False
